// The "Coach's take" - a short, plain-language read on the user's OWN betting
// history, generated by Claude. Deliberately framed as a mirror, not a tipster:
// it reflects staking discipline and patterns already in the data (see
// src/pages/InsightsPage.jsx), and is prompted never to predict outcomes or
// suggest bets, in keeping with BetMates' trust-based, never-places-real-bets
// design.
//
// The client sends an already-aggregated summary (counts, win rate, P&L, top
// sport/market, streaks) - never raw bet rows - so nothing identifying leaves
// the browser and the request body stays tiny. Stateless: no storage, no auth
// lookups, just summary in -> coaching out.
//
// Missing ANTHROPIC_API_KEY degrades like every other proxy here: it returns
// { configured: false } (HTTP 200) and the UI simply hides the section rather
// than erroring. Set ANTHROPIC_API_KEY in the Netlify env to switch it on.

const MODEL = 'claude-opus-5'
const ANTHROPIC_VERSION = '2023-06-01'

function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'content-type': 'application/json' }
  })
}

// Turn the client's summary object into a compact, model-friendly briefing.
// Everything is optional - a brand-new user might only have a couple of fields
// - so each line is guarded and skipped when absent.
function briefing(s) {
  const lines = []
  if (Number.isFinite(s.settled)) lines.push(`Settled bets: ${s.settled}`)
  if (Number.isFinite(s.winRate)) lines.push(`Win rate: ${s.winRate}%`)
  if (Number.isFinite(s.profit)) lines.push(`Net P&L: ${s.profit >= 0 ? '+' : ''}£${s.profit.toFixed(2)}`)
  if (Number.isFinite(s.roi)) lines.push(`ROI: ${s.roi >= 0 ? '+' : ''}${s.roi.toFixed(1)}%`)
  if (Number.isFinite(s.avgStake)) lines.push(`Average stake: £${s.avgStake.toFixed(2)}`)
  if (Number.isFinite(s.biggestStake)) lines.push(`Biggest single stake: £${s.biggestStake.toFixed(2)}`)
  if (s.topSport) lines.push(`Most profitable sport: ${s.topSport}`)
  if (s.worstSport) lines.push(`Least profitable sport: ${s.worstSport}`)
  if (s.topMarket) lines.push(`Best market by win rate: ${s.topMarket}`)
  if (s.favBookmaker) lines.push(`Most used bookmaker: ${s.favBookmaker}`)
  if (Number.isFinite(s.avgOdds)) lines.push(`Average odds taken: ${s.avgOdds.toFixed(2)}`)
  if (Number.isFinite(s.accaShare)) lines.push(`Share of bets that are accumulators: ${s.accaShare}%`)
  if (Number.isFinite(s.currentStreak) && s.currentStreak !== 0)
    lines.push(`Current streak: ${Math.abs(s.currentStreak)} ${s.currentStreak > 0 ? 'wins' : 'losses'} in a row`)
  return lines.join('\n')
}

const SYSTEM = [
  'You are the "Coach" inside BetMates, a social betting tracker. Users log',
  'their own bets; the app never places real bets and shows no live money.',
  'You are given a summary of ONE user\'s past betting record and write them a',
  'short, friendly, honest read on it.',
  '',
  'Hard rules:',
  '- Never predict a result, name a team/player to back, or suggest a bet. You',
  '  reflect the record that already exists; you do not tip.',
  '- Focus on habits and discipline: staking consistency, chasing losses,',
  '  favourite markets, where the record is strong vs weak, bankroll sense.',
  '- Be candid but kind. If the record is losing, say so plainly and gently.',
  '- Keep it grounded in the numbers you were given. Do not invent figures.',
  '- If the numbers look like heavy or escalating betting, work in a light,',
  '  non-preachy nudge toward the safer-gambling tools in the app.',
  '',
  'Format: 2-4 short sentences (or up to 3 tight bullet points). No preamble,',
  'no sign-off, no emoji spam - at most one. British English, pub-mate tone.'
].join('\n')

export default async (req) => {
  if (req.method !== 'POST') return json({ configured: true, error: 'POST only' }, 405)

  const apiKey = process.env.ANTHROPIC_API_KEY
  if (!apiKey) return json({ configured: false })

  let summary
  try {
    summary = (await req.json())?.summary
  } catch {
    return json({ configured: true, error: 'Bad request body' }, 400)
  }

  const brief = briefing(summary ?? {})
  // Below a couple of settled bets there's nothing worth coaching on, and we'd
  // rather not spend a token on "not enough data" - the UI gates on this too.
  if (!brief || !(summary?.settled >= 2)) return json({ configured: true, take: null })

  try {
    const res = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': ANTHROPIC_VERSION
      },
      body: JSON.stringify({
        model: MODEL,
        max_tokens: 350,
        system: SYSTEM,
        messages: [{ role: 'user', content: `Here is my BetMates record:\n\n${brief}\n\nGive me your take.` }]
      })
    })
    if (!res.ok) {
      const detail = await res.text().catch(() => '')
      console.error(`coach: Anthropic ${res.status}: ${detail.slice(0, 300)}`)
      // Upstream trouble degrades to "unavailable" rather than a hard error, so
      // the Insights page still renders everything else.
      return json({ configured: true, take: null })
    }
    const data = await res.json()
    const take = data?.content?.find((b) => b.type === 'text')?.text?.trim() ?? null
    return json({ configured: true, take })
  } catch (err) {
    console.error('coach: request failed:', err.message)
    return json({ configured: true, take: null })
  }
}
