// The Coach - short, plain-language reads generated by Claude, always framed
// as a mirror, not a tipster (the prompts and never-tip rules live in
// src/lib/coach.js, shared with the weekly coach push so the voices can't
// drift apart). One endpoint, three request shapes:
//   { summary }  - "Coach's take" on the user's whole record (Insights)
//   { bet }      - "bet review" on ONE of the user's own settled bets (Tracker)
//   { recap }    - "group Coach" on a group's week together (group feed)
// Each sends already-aggregated numbers - never raw bet rows - so nothing
// identifying leaves the browser and the request body stays tiny. Stateless:
// data in, coaching out.
//
// Missing COACH_ANTHROPIC_KEY degrades like every other proxy here: it returns
// { configured: false } (HTTP 200) and the UI simply hides/skips rather than
// erroring. Set COACH_ANTHROPIC_KEY in the Netlify env to switch it on - named
// that rather than ANTHROPIC_API_KEY because Netlify's AI Gateway silently
// intercepts the latter in local `netlify dev` (see coachgpt.js for the full
// story); production was never affected, but the rename sidesteps it everywhere.
import { createClient } from '@supabase/supabase-js'
import { requestCoachTake } from '../../src/lib/coach.js'

const SUPABASE_URL = process.env.VITE_SUPABASE_URL
const ANON_KEY = process.env.VITE_SUPABASE_ANON_KEY

function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'content-type': 'application/json' }
  })
}

// This function is reachable directly over HTTP by anyone, not just through
// the app's own UI - unlike coachgpt.js (which has a real free/Plus message
// cap to enforce), this feature has no per-user limit of its own, so this
// isn't rate-limiting, just identity. Confirmed live: with no check at all
// here, a fully signed-out caller with no account could still generate real
// Claude completions against invented bet-shaped data, burning the same
// COACH_ANTHROPIC_KEY budget coachgpt.js is trying to meter. Same
// missing-Supabase-config-degrades-to-open contract as checkMessageAllowance
// in coachgpt.js - only a genuinely unconfigured (local/no-backend) deploy
// skips this.
async function isRealUser(accessToken) {
  if (!SUPABASE_URL || !ANON_KEY) return true
  if (!accessToken) return false
  const userClient = createClient(SUPABASE_URL, ANON_KEY, { global: { headers: { Authorization: `Bearer ${accessToken}` } } })
  const { data, error } = await userClient.auth.getUser()
  return !error && !!data?.user
}

export default async (req) => {
  if (req.method !== 'POST') return json({ configured: true, error: 'POST only' }, 405)

  const apiKey = process.env.COACH_ANTHROPIC_KEY
  if (!apiKey) return json({ configured: false })

  let body
  try {
    body = await req.json()
  } catch {
    return json({ configured: true, error: 'Bad request body' }, 400)
  }

  if (!(await isRealUser(body?.accessToken))) return json({ configured: true, take: null })

  // Bet review - only settled bets are worth a reaction; an open bet has no
  // outcome to react to.
  if (body?.bet) {
    if (!body.bet.status || body.bet.status === 'open') return json({ configured: true, take: null })
    const take = await requestCoachTake({ bet: body.bet, apiKey, style: 'bet' })
    return json({ configured: true, take })
  }

  // Group Coach - needs at least one settled bet this week to have anything
  // to say, same "don't spend a token on nothing" rule as the other styles.
  if (body?.recap) {
    if (!(body.recap.settledCount >= 1)) return json({ configured: true, take: null })
    const take = await requestCoachTake({ recap: body.recap, apiKey, style: 'group' })
    return json({ configured: true, take })
  }

  // Coach's take on the whole record (unchanged). Below a couple of settled
  // bets there's nothing worth coaching on, and we'd rather not spend a token
  // on "not enough data" - the UI gates on this too.
  if (!(body?.summary?.settled >= 2)) return json({ configured: true, take: null })

  const take = await requestCoachTake({ summary: body.summary, apiKey, style: 'full' })
  return json({ configured: true, take })
}
